import {
  Award,
  Baby,
  Banknote,
  Bitcoin,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CalendarClock,
  Car,
  ChartCandlestick,
  ChartLine,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  FileText,
  Fuel,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  HeartPulse,
  Home,
  Landmark,
  LandPlot,
  Laptop,
  Layers,
  Mailbox,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  RotateCcw,
  Scissors,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Tag,
  Ticket,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icon names stored in expense_categories.icon / asset_categories.icon →
 * lucide component. Every icon used by a default category in the migrations
 * must be listed here, otherwise `CategoryIcon` falls back to the tag glyph.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // expense defaults
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  car: Car,
  fuel: Fuel,
  'shopping-bag': ShoppingBag,
  receipt: Receipt,
  'building-2': Building2,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  clapperboard: Clapperboard,
  plane: Plane,
  scissors: Scissors,
  repeat: Repeat,
  shield: Shield,
  landmark: Landmark,
  'trending-up': TrendingUp,
  baby: Baby,
  'paw-print': PawPrint,
  'hand-heart': HandHeart,
  gift: Gift,
  tag: Tag,
  // income defaults
  briefcase: Briefcase,
  store: Store,
  laptop: Laptop,
  percent: Percent,
  sparkles: Sparkles,
  'rotate-ccw': RotateCcw,
  'hand-coins': HandCoins,
  coins: Coins,
  // asset / debt type defaults
  'chart-candlestick': ChartCandlestick,
  'chart-line': ChartLine,
  layers: Layers,
  'shield-check': ShieldCheck,
  'file-text': FileText,
  handshake: Handshake,
  gem: Gem,
  'land-plot': LandPlot,
  bitcoin: Bitcoin,
  mailbox: Mailbox,
  award: Award,
  'credit-card': CreditCard,
  'calendar-clock': CalendarClock,
  // extras for custom categories
  home: Home,
  smartphone: Smartphone,
  wifi: Wifi,
  dumbbell: Dumbbell,
  wrench: Wrench,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  coffee: Coffee,
  shirt: Shirt,
  'book-open': BookOpen,
  pill: Pill,
  users: Users,
  ticket: Ticket,
  bus: Bus,
}

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS)

export const CATEGORY_COLORS = [
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#84cc16',
  '#22c55e',
  '#10b981',
  '#14b8a6',
  '#06b6d4',
  '#0ea5e9',
  '#3b82f6',
  '#6366f1',
  '#8b5cf6',
  '#a855f7',
  '#ec4899',
  '#f43f5e',
  '#ef4444',
  '#64748b',
]
